name: Sloth Shots
favicon: null
layout_spectrum: 0.5884821040090173
typography_spectrum: 0.16633549495600164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.34407780040055513
  lightness: 0.2454296809155494
  saturation: 0.6987829513382167
  rhythmicContrast: 0.8067490449175239
purpose: []
